### ISSUE TITLE
[🐛Bug] Server crashes if all cards from deck are exhausted

### ISSUE THREAD

**Issue by notvalproate** [notvalproate/Algo-Game#16]
### Describe the bug

When the players keep playing and do not finish the game before exhausting all the cards, the server tries to splice from an empty array causing the server to crash. The bug occurs in the game.js module where the insertDeckTopToActiveUser() function is called every time the turns switch.

Here is a permalink to where the error occurs:
https://github.com/notvalproate/Algo-Game/blob/9fd8db0c1a1c19dc475ab510228d1b104c7c5d0d/modules/game.js#L47

### Steps To Reproduce

1. Run the server locally on your machine
2. Open two tabs or devices and join the same room
3. Click ready on both tabs or devices and start playing
4. Keep playing without letting either tab / device win until the deck gets exhausted and both players have 12 cards each.
5. On the next move the server crashes since there are no cards left in the deck.

### Expected Behavior

An implementation of a tie between the players must be added. This includes adding a new parameter to the game-ended socket event called 'tie' or something like that. The players should see "YOU TIED"  as the text and display a neutral blue color rather than red or green. Neither of the players should gain any wins in the head-to-head stats section. 

### Additional context

This will require a ja translation added as well for the tie-ing texts. A seperate branch will be made for that and a pull-request into that branch should suffice.

### Are you working on this issue?

No

**Comment by Manoj-E-S** [comment]
Hello! I'll take this up. It's a nice game I wouldn't want it to crash even in the edge-most of the cases.

**Comment by notvalproate** [comment]
@Manoj-E-S Thanks! be sure to link this issue to your PR once you make the PR.

**Comment by Manoj-E-S** [comment]
Okay @notvalproate . I'll make sure to do that.

**Comment by notvalproate** [comment]
![image](https://github.com/user-attachments/assets/d1c1e738-1275-4b4f-8480-ea42f4d5d3ab)
