### ISSUE TITLE
Remove the confetti effect when a player loses

### ISSUE THREAD

**Issue by SaekaMiyake** [notvalproate/Algo-Game#6]
It seems odd that confetti appears when a player loses. I suggest that the confetti effect is removed.

**Comment by notvalproate** [comment]
@AntrikshNarang

**Comment by notvalproate** [comment]
Apologies for accidentally closing the issue, honest misclick.
@AntrikshNarang should I assign you?

**Comment by mshokoya** [comment]
claim

**Comment by notvalproate** [comment]
@mshokoya Thanks for the contribution. Just a small issue, the confetti now shows up before the results of the game show up, so the displayConfetti() function must be called within the setTimeout at line 354, for the confetti to show up in sync with the display of the results.

https://github.com/mshokoya/Algo-Game/blob/a3fd76f7af274a2610f6abd140df6764f89b5e6d/public/dev/js/helpers.js#L336C1-L357C2

If you want you can remove the wonGame parameter from the displayConfetti function entirely as the confetti doesn't need to change color and position on whether the player won or lost anymore. 

Update your branch and I'll merge it and close this issue!

**Comment by AntrikshNarang** [comment]
Is the issue resolved?

**Comment by notvalproate** [comment]
> Is the issue resolved?

@AntrikshNarang  Not yet, should I assign you the issue?

**Comment by mshokoya** [comment]
@notvalproate Changes have been made, sorry for the late response.

**Comment by notvalproate** [comment]
> @notvalproate Changes have been made, sorry for the late response.

No issues! Thank you so much for the contribution!
