### ISSUE TITLE
[🐛Bug] Same username able to join if both click play at the same time

### ISSUE THREAD

**Issue by Kunal-JockL** [notvalproate/Algo-Game#8]
### Describe the bug

if two people with the same username click the play button at the same time both players can join the lobby with the same username.

### Steps To Reproduce

1. Open the site on two different windows or devices.
2. Enter the same username and the same room key in both.
3. Press play at exactly/about the same time
4. Both players now have the same username in the same lobby

### Expected Behavior

The player that made the GET request after the first one should be sent back to the create room page

### Screenshots

![image](https://github.com/notvalproate/Algo-Game/assets/109150464/b84d88a8-c420-4f94-945b-8dee64fb56db)

### Are you working on this issue?

No

**Comment by AntrikshNarang** [comment]
Happy to resolve this issue!
