### ISSUE TITLE
[🐛Bug] The socket.io script linked in the header is not minified

### ISSUE THREAD

**Issue by notvalproate** [notvalproate/Algo-Game#9]
### Describe the bug

The socket.io.js script in the _header.ejs partial is the unminified version of socket.io

### Steps To Reproduce

Method 1:
1. Go to the website https://playalgo.com
2. Press F12 / Open developer tools
3. Go to the elements tab and expand the header tag of the website
4. Scroll down to see the unminfied socket.io script linked

Method 2:
1. Go to https://github.com/notvalproate/Algo-Game/blob/6cae057d18c5192f066fc07ed7259d6abf67a536/views/partials/_header.ejs
2. Scroll down to see the unminfied socket.io script linked

### Expected Behavior

Expected the minified version of socket.io to be linked instead.

### Are you working on this issue?

No

**Comment by Kenny4297** [comment]
@notvalproate I have the solution! May I create a PR?

**Comment by notvalproate** [comment]
@Kenny4297 Sure, I'll assign you.
